[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle embed scripts
[[redirects]]
  from = "/embed/:id.js"
  to = "/api/embed/:id"
  status = 200
  force = true

# Handle all other routes for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200